# Generated by Django 3.0.6 on 2020-05-28 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coder',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('age', models.DecimalField(decimal_places=0, max_digits=3)),
                ('type', models.CharField(max_length=10)),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'coder',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Commits',
            fields=[
                ('time_stamp', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('file_name', models.CharField(blank=True, max_length=50, null=True)),
                ('commit_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'commits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('e_id', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('extension', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('file_type', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'extension',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('file_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('size', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'files',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('repo_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('ctime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'repository',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('job_desc', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'salary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('ip', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'server',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Starred',
            fields=[
                ('username', models.OneToOneField(db_column='username', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='hub_base.Coder')),
                ('rating', models.DecimalField(decimal_places=0, max_digits=1)),
            ],
            options={
                'db_table': 'starred',
                'managed': False,
            },
        ),
    ]
